### ISSUE TITLE
ROS2 - No solution to use Waffle Pi with OpenManipulator-X?

### ISSUE THREAD

**Issue by joaoramosipl** [ROBOTIS-GIT/open_manipulator_with_tb3#1]
Hello,
I'm using a Waffle Pi and OpenManipulator-X, connected via the OpenCR.
Although, I'm having troubles to use the OpenManipulator with the OpenCR fw for TurtleBot. I can use the arm when I install the usb_to_dxl application in the OpenCR, but then I lose the wheel/LIDAR functions. Can you please help me?

I believe that this package would solve my problem, but it's deprecated and won't even compile in Foxy.

Thanks

**Comment by ROBOTIS-Will** [comment]
Hi @joaoramosipl 

At the moment ROS2 TurtleBot3 Manipulation using the OpenMANIPULATOR-X is supported with Dashing, and being updated to Foxy.
You may find the instruction for Dashing in the below eManual.
Please make sure to select the `Dashing` at the top of the page.
https://emanual.robotis.com/docs/en/platform/turtlebot3/manipulation

Thank you.

**Comment by joaoramosipl** [comment]
Hello, thanks for your fast response.
My question now is how can I configure the OpenCR, to be listening for the OpenMANIPULATOR-X commands? The only source code for TurtleBot3 + OM in the OpenCR library that I find is for ROS1.
Thanks once again.

**Comment by ROBOTIS-Will** [comment]
Oh, sorry about the misleading information.
You don't need additional firmware for ROS2 TB3 manipulation.
You can use the same firmware for the Dashing as OpenCR will redirect received packets to each DYNAMIXEL.
Thanks!

**Comment by goekce** [comment]
@ROBOTIS-Will 
> At the moment ROS2 TurtleBot3 Manipulation using the OpenMANIPULATOR-X is supported with Dashing, and being updated to Foxy. 

When do you plan to release TurtleBot3 Manipulation using the OpenMANIPULATOR-X for foxy/rolling?

**Comment by ROBOTIS-Will** [comment]
Hi @goekce 
I'm setting up the project schedule of this year which includes some delayed plans from last year.
More specific plan should be available in February, but TB3 OM-X ROS2 is one of the priority projects.
Thank you.

**Comment by RubenCarreira99** [comment]
Hi @ROBOTIS-Will, I came across the same issue here. Are there any updates regarding this?

**Comment by joaoramosipl** [comment]
Apparently, this issue seems to be fixed:

https://github.com/ROBOTIS-GIT/OpenCR/releases/tag/1.5.2

Waffle Manipulator was now included as a new model.

**Comment by ROBOTIS-Will** [comment]
@RubenCarreira99 
You may find more information from the eManual below.
Make sure to select "Foxy" at the top of the page.
https://emanual.robotis.com/docs/en/platform/turtlebot3/manipulation/#manipulation
Thanks!
